### ISSUE TITLE
Verwijder de knop "production entities enabled"

### ISSUE THREAD

**Issue by phavekes** [SURFnet/sp-dashboard#1145]
[This issue is imported from pivotal - Originaly created at Feb 15, 2024 by Bart Geesink](https://www.pivotaltracker.com/story/show/187053888)

In het "edit service" overzicht staat een optie" production entities enabled" . Deze optie is om voor sommige services het production entities overzicht te verbergen. Deze lijkt al vrij lang niet te werken en kan weggehaald worden.

**Comment by phavekes** [comment]
Dit gaan we niet doen, dus deze mag gesloten worden (Teun Fransen - Jul 4, 2024)

**Comment by johanib** [comment]
This was already merged, so is reverted in https://github.com/SURFnet/sp-dashboard/pull/1293
Including a migration to restore the column in case it was already deployed to test (or other environments).

**Comment by johanib** [comment]
@teunfransen This has been merged to main.
