### ISSUE TITLE
Vul waarde coin:contractual_base  bij productieaanvragen

### ISSUE THREAD

**Issue by phavekes** [SURFnet/sp-dashboard#1155]
[This issue is imported from pivotal - Originaly created at Jul 18, 2024 by Teun Fransen](https://www.pivotaltracker.com/story/show/187977233)

Bij het publiceren van een dienst naar de productieomgeving van SURFconext, moet het veld coin:contractual_base meegenomen worden

Als het een Instellings SP  betreft(service_type = institute) mag van de gepubliceerde entity het coin:contractual_base veld gevuld worden met waarde \'IX\' Dit geldt voor type SAML SP en OIDC RP. 

Als het een SP betreft (service_type =none-institute) mag de gepubliceerde entity het coin:contractual_base veld gevuld worden met waarde \'AO\'

**Comment by phavekes** [comment]
Gaat nu (Teun Fransen - Aug 21, 2024)

**Comment by teunfransen** [comment]
https://github.com/SURFnet/sp-dashboard/pull/665
