### ISSUE TITLE
IdP invite request: invite versturen zonder op het +je te klikken

### ISSUE THREAD

**Issue by phavekes** [SURFnet/sp-dashboard#1201]
![Image](https://github.com/user-attachments/assets/0dde1fef-e127-45fb-8a66-4dec3a5e0470)
[This issue is imported from pivotal - Originaly created at Feb 8, 2023 by Teun Fransen](https://www.pivotaltracker.com/story/show/184424190)

Als gebruiker wil ik een instelling kunnen uitnodigen zonder dat ik perse op het +je hoef te drukken. Met andere woorden; als de drie velden gevuld zijn, wordt de \'send\' button actief. 

1. Gebruiker vult koppelverzoek in
2. Formulier unlocked de send button
3. Formulier wordt toegevoegd aan de lijst van ingevulde change requests
4. Formulier wordt gevalideerd
5. Formulier wordt opgeslagen.

Spike doen, om bovenstaand gedrag te bewerkstelligen. Als lastig, dan terug naar de tekentafel.

**Comment by phavekes** [comment]
Optie voor als we terug naar de tekentafel moeten. Waarbij de tekst een placeholder is. In de plaats van \'nothing here. Fill out the form and press +\' komt de inhoud van het ingevulde formuliertje. Send wordt pas actief als het eerste contact is toegevoegd (zoals het nu werkt) (Teun Fransen - Jul 12, 2023)

**Comment by teunfransen** [comment]
![Image](https://github.com/user-attachments/assets/bfe4ceae-81a7-4246-9189-5dabd8ceb8d7)
